services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  temporal:
    container_name: temporal
    depends_on:
      - postgres
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=myuser
      - POSTGRES_PWD=secret
      - POSTGRES_SEEDS=postgres
    image: temporalio/auto-setup:1.22.7
    ports:
      - 7233:7233
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - temporal
      - postgres
    labels:
      org.springframework.boot.ignore: true